using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace PlaySlot.Agent.Ipc;

/// <summary>
/// HMAC-SHA256 signing for the control-server link, matching the server's canonical form
/// byte for byte.
///
/// The signed bytes are:
///
///     unit_id \n message_type \n timestamp \n nonce \n body_json
///
/// where body_json has its keys sorted and no whitespace. Newline separates the fields
/// because it cannot occur in a UUID, a message type or a number, so no field can be
/// shifted into its neighbour.
///
/// Three things here exist purely to match Python, and each one silently breaks every
/// signature if it is changed:
///
///   * <see cref="JavaScriptEncoder.UnsafeRelaxedJsonEscaping"/>. System.Text.Json escapes
///     '&lt;', '&gt;' and '&amp;' by default as an HTML-injection defence. Python does not,
///     so the default turns any body containing those characters into a mismatch. The name
///     sounds alarming but nothing here is ever written into an HTML page.
///   * Keys sorted with <see cref="StringComparer.Ordinal"/> — by UTF-16 code unit, which
///     is what Python's sort_keys does. Culture-aware ordering would disagree on case and
///     accents depending on the machine's locale, so the same message would sign
///     differently on two PCs in the same cafe.
///   * Bodies restricted to string, integer, boolean and null. Floating point has no
///     single canonical rendering: Python writes 1.0 where .NET writes 1.
///
/// Verified against shared vectors in signing-vectors.json, generated by the server.
/// </summary>
internal static class MessageSigner
{
    private static readonly JsonSerializerOptions BodyOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        WriteIndented = false,
    };

    /// <summary>The exact bytes the signature covers.</summary>
    public static byte[] CanonicalBytes(
        string unitId, string messageType, long timestamp, string nonce, JsonObject body)
    {
        var canonical =
            $"{unitId}\n{messageType}\n{timestamp}\n{nonce}\n{CanonicalJson(body)}";

        return Encoding.UTF8.GetBytes(canonical);
    }

    /// <summary>Serialises a body with sorted keys and no whitespace.</summary>
    public static string CanonicalJson(JsonNode? node)
    {
        // Built by hand rather than by the serialiser because System.Text.Json preserves
        // insertion order for objects, and the server sorts. Two agents that happened to
        // build the same body in a different order would otherwise sign differently.
        var buffer = new StringBuilder();
        WriteCanonical(node, buffer);
        return buffer.ToString();
    }

    private static void WriteCanonical(JsonNode? node, StringBuilder buffer)
    {
        switch (node)
        {
            case null:
                buffer.Append("null");
                return;

            case JsonObject obj:
            {
                buffer.Append('{');

                var first = true;

                // Ordinal: by UTF-16 code unit, exactly as Python's sort_keys orders.
                foreach (var property in obj.OrderBy(p => p.Key, StringComparer.Ordinal))
                {
                    if (!first)
                    {
                        buffer.Append(',');
                    }

                    first = false;

                    buffer.Append(JsonSerializer.Serialize(property.Key, BodyOptions));
                    buffer.Append(':');
                    WriteCanonical(property.Value, buffer);
                }

                buffer.Append('}');
                return;
            }

            case JsonArray array:
            {
                buffer.Append('[');

                for (var i = 0; i < array.Count; i++)
                {
                    if (i > 0)
                    {
                        buffer.Append(',');
                    }

                    WriteCanonical(array[i], buffer);
                }

                buffer.Append(']');
                return;
            }

            case JsonValue value:
                WriteValue(value, buffer);
                return;

            default:
                throw new InvalidOperationException($"Uncanonical node type {node.GetType().Name}");
        }
    }

    private static void WriteValue(JsonValue value, StringBuilder buffer)
    {
        if (value.TryGetValue<bool>(out var boolean))
        {
            buffer.Append(boolean ? "true" : "false");
            return;
        }

        if (value.TryGetValue<string>(out var text))
        {
            buffer.Append(JsonSerializer.Serialize(text, BodyOptions));
            return;
        }

        if (value.TryGetValue<long>(out var integer))
        {
            buffer.Append(integer.ToString(System.Globalization.CultureInfo.InvariantCulture));
            return;
        }

        // Reached only for floating point or a type the server would also reject. Failing
        // here is far better than emitting a body that signs differently at the far end,
        // where it would surface as an unexplained authentication failure.
        throw new InvalidOperationException(
            $"Value '{value.ToJsonString()}' has no canonical form shared with the server; " +
            "use a string, integer, boolean or null.");
    }

    public static string Sign(
        string secret, string unitId, string messageType, long timestamp, string nonce, JsonObject body)
    {
        using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(secret));

        var hash = hmac.ComputeHash(CanonicalBytes(unitId, messageType, timestamp, nonce, body));

        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    /// <summary>A complete signed envelope, ready to send.</summary>
    public static JsonObject BuildEnvelope(
        string secret, string unitId, string messageType, JsonObject body)
    {
        var timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var nonce = Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();

        return new JsonObject
        {
            ["unit_id"] = unitId,
            ["type"] = messageType,
            ["ts"] = timestamp,
            ["nonce"] = nonce,
            ["body"] = body.DeepClone(),
            ["sig"] = Sign(secret, unitId, messageType, timestamp, nonce, body),
        };
    }

    /// <summary>
    /// Verifies an inbound envelope and returns its body, or null if it fails.
    ///
    /// The agent verifies server messages for the same reason the server verifies the
    /// agent's: an unsigned server-to-agent channel would let anyone on the cafe wifi
    /// send this machine a forged unlock without ever touching the control server.
    /// </summary>
    public static JsonObject? Verify(string secret, JsonObject envelope, int freshnessSeconds = 30)
    {
        try
        {
            var unitId = envelope["unit_id"]?.GetValue<string>();
            var messageType = envelope["type"]?.GetValue<string>();
            var timestamp = envelope["ts"]?.GetValue<long>();
            var nonce = envelope["nonce"]?.GetValue<string>();
            var presented = envelope["sig"]?.GetValue<string>();
            var body = envelope["body"]?.AsObject();

            if (unitId is null || messageType is null || timestamp is null ||
                nonce is null || presented is null || body is null)
            {
                return null;
            }

            var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();

            if (Math.Abs(now - timestamp.Value) > freshnessSeconds)
            {
                Log.Warn("Rejected a server message outside the freshness window (clock skew?)");
                return null;
            }

            var expected = Sign(secret, unitId, messageType, timestamp.Value, nonce, body);

            // Constant-time. A plain string comparison leaks how many leading characters
            // matched, which is enough to reconstruct a signature byte by byte.
            var matches = CryptographicOperations.FixedTimeEquals(
                Encoding.UTF8.GetBytes(expected), Encoding.UTF8.GetBytes(presented));

            return matches ? body : null;
        }
        catch (Exception ex)
        {
            Log.Warn($"Malformed server message: {ex.Message}");
            return null;
        }
    }
}
