"""seven tables

Revision ID: 35e0c3c98b36
Revises: 
Create Date: 2026-08-12 18:18:38.066654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e0c3c98b36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('is_append_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index('ix_activity_venue_time', ['venue_id', 'timestamp'], unique=False)

    op.create_table('pricing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('unit_type', sa.String(length=32), nullable=False),
    sa.Column('hourly_rate_paise', sa.BigInteger(), nullable=False),
    sa.Column('overtime_rate_paise_per_minute', sa.BigInteger(), nullable=False),
    sa.Column('controller_surcharge_paise_per_hour', sa.BigInteger(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index('ix_pricing_lookup', ['venue_id', 'unit_type', 'effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_unit_type'), ['unit_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_venue_id'), ['venue_id'], unique=False)

    op.create_table('sync_outbox',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_outbox_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_outbox_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_outbox_synced_at'), ['synced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_outbox_venue_id'), ['venue_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_session_id', sa.String(length=36), nullable=True),
    sa.Column('relay_address', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index('ix_units_venue_state', ['venue_id', 'state'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('device_token', sa.String(length=128), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_verifications', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_unit_id'), ['unit_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agents_venue_id'), ['venue_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('customer_ref', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('extensions', sa.JSON(), nullable=False),
    sa.Column('rate_snapshot_paise', sa.BigInteger(), nullable=False),
    sa.Column('overtime_rate_paise_per_minute', sa.BigInteger(), nullable=False),
    sa.Column('controller_surcharge_paise_per_hour', sa.BigInteger(), nullable=False),
    sa.Column('extra_controllers', sa.Integer(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index('ix_sessions_unit_status', ['unit_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index('ix_sessions_venue_status', ['venue_id', 'status'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_settled_at'), ['settled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index('ix_sales_venue_settled', ['venue_id', 'settled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_venue_settled')
        batch_op.drop_index(batch_op.f('ix_sales_venue_id'))
        batch_op.drop_index(batch_op.f('ix_sales_settled_at'))
        batch_op.drop_index(batch_op.f('ix_sales_session_id'))

    op.drop_table('sales')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_venue_status')
        batch_op.drop_index(batch_op.f('ix_sessions_venue_id'))
        batch_op.drop_index('ix_sessions_unit_status')
        batch_op.drop_index(batch_op.f('ix_sessions_unit_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_venue_id'))
        batch_op.drop_index(batch_op.f('ix_agents_unit_id'))

    op.drop_table('agents')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_venue_state')
        batch_op.drop_index(batch_op.f('ix_units_venue_id'))

    op.drop_table('units')
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_outbox_venue_id'))
        batch_op.drop_index(batch_op.f('ix_sync_outbox_synced_at'))
        batch_op.drop_index(batch_op.f('ix_sync_outbox_event_type'))
        batch_op.drop_index(batch_op.f('ix_sync_outbox_created_at'))

    op.drop_table('sync_outbox')
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_venue_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_unit_type'))
        batch_op.drop_index('ix_pricing_lookup')
        batch_op.drop_index(batch_op.f('ix_pricing_effective_from'))

    op.drop_table('pricing')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_venue_time')
        batch_op.drop_index(batch_op.f('ix_activity_log_venue_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_unit_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_event'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
