"""inventory and session items

Adds the inventory table and the sessions.items column (snacks and drinks rung up against
a tab).

One correction to what autogenerate produced: sessions.items is NOT NULL, and a NOT NULL
column with no default fails the instant there is an existing session row — and every venue
running this has a full evening of them. It is added with a server default of an empty JSON
array, which is what a session with no items already means, then the default is dropped so
new rows come from the model's ``default=list`` instead.

Revision ID: bd1db431db6a
Revises: 9cdd5d26260d
Create Date: 2026-08-20 06:13:57.890411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1db431db6a'
down_revision: Union[str, Sequence[str], None] = '9cdd5d26260d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_venue', ['venue_id', 'archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('items', sa.JSON(), nullable=False, server_default='[]')
        )

    # The default has done its job (filling existing rows) and is dropped, so the schema
    # matches the model, which carries the default in Python.
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('items', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('items')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_venue_id'))
        batch_op.drop_index('ix_inventory_venue')

    op.drop_table('inventory')
    # ### end Alembic commands ###
